#!/usr/bin/python3
from sys import argv, exit
from cal import days_name, is_now, month, now, today, weeks_to_str

show_month = True
params = argv[1:]
for v in reversed(params):
    if v[:7] + v[-1:] == '${font }':
        font = v
        params.remove(v)
    if v == '--no-month':
        show_month = False
        params.insert(0, '')
        params.remove(v)

len_param = 4 - len(params)
if len_param > 1:
    params.extend(len_param * ['$color'])
elif len_param == 1:
    params.append('$color')
elif len_param < 0:
    print ('Demasiados parámetros…')
    exit(0)

spaces = 0

if params[-1].isdecimal():
    spaces = int(params[-1])
    params = params[:-1]

month_year_hr, names, mark, default = params

month = weeks_to_str('--', month)

while len(month) < 6:
    month.append(['--'] * 7)

month[-1][-1] = month[-1][-1] + '${color}'

for i, w in enumerate(month):
    month[i] = [is_now(d, today, mark, f'{default}') for d in month[i]]
month.insert(0, days_name)
if 'font' in locals():
    month[0][0] = f'{font}{month[0][0]}'
    month[-1][-1] = month[-1][-1] + '$font'
if show_month:
    month_year = now.strftime('%B %Y').title() + f' $hr{default}'
    print (month_year_hr + month_year)
for i, w in enumerate(month):
    if i == 0:
        print ('${alignc}' + names + "  ".join(w) + default)
    else:
        print ('${alignc}' + '  '.join(w))
