#!/usr/bin/python3
from sys import argv, exit
from cal import days_name, is_now, month, now, today, weeks_to_str

if len(argv) == 1:
    argv.extend(3 * ['$color'])
elif len(argv) == 2:
    argv.extend(2 * ['$color'])
elif len(argv) == 3:
    argv.append('$color')
elif len(argv) > 4:
    exit(1)

params = argv[1:]
spaces = 0

if params[-1].isdecimal():
    spaces = int(params[-1])
    params = params[:-1]

names, mark, default = params

month = weeks_to_str('--', month)

while len(month) < 6:
    month.append(['--'] * 7)

month[-1][-1] = month[-1][-1] + '${color}'

for i, w in enumerate(month):
    month[i] = [is_now(d, today, mark, f'{default}') for d in month[i]]
month.insert(0, days_name)
print (now.strftime('%B %Y').title() + f' $hr{default}')
for i, w in enumerate(month):
    if i == 0:
        print (f'$alignc{names}{"  ".join(w)}{default}')
    else:
            print ('${alignc}' + '  '.join(w))
